### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:18334

### ISSUE THREAD

**Issue by HOllarves** [bcoin-org/bcoin-docker#9]
Hello guys! I've been struggling to implement this docker container in my docker-compose for a couple of days. I am able to correctly run bcoin docker container and provide it with a config file that effectively starts a bcoin node in the testnet with prune mode:

**bcoin.conf:**
```
# main, testnet
network: testnet

# Data directory
prefix: media/henry/Code/bcoin

# Enable flags
use-workers: true

log-file: true
log-level: info
max-files: 8192
prune: true

http-host: 0.0.0.0
api-key: secret123
```

**wallet.conf**
```
network: testnet
prefix: /media/henry/Code/bcoin
http-host: 0.0.0.0
```
 However, when trying to commnicate with my application container, for example when trying to create a wallet like so:

```
	const { Network } = require("bcoin")
	const { WalletClient } = require("bclient")
	const network = Network.get("testnet")
	const walletOptions = {
		network: network.type,
		port: network.walletPort,
		apiKey: "secret123"
	}
	/**
	 * Initializes wallet from predefined mnemonic seed
	 */
	const initWallet = async () => {
		try {
			const walletClient = new WalletClient(walletOptions)
			const id = "primary"
			const wallet = walletClient.wallet(id)
			return wallet
		} catch (e) {
			throw new Error(e)
		}
	}
	const wallet = await initWallet()
	/**
	 * Adds a new account to the bcoin wallet
	 * @param {*} req 
	 * @param {*} res 
	 */
	const addUserAccount = async (req, res) => {
		const id = req.body.userId.split("|")[1]
		try {
			const userAccount = await wallet.createAccount(id)
			return userAccount
		} catch (e) {
			throw new Error(e)
		}
	}

	addUserAccount({ body: { userId: "auth0|23534576457" } })
```
I get a econnrefused error:

```
 Error: connect ECONNREFUSED 127.0.0.1:18334
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
```

Here's my docker-compose (I just copied and pasted it from this repo and added my own application container to the network:

```
version: '2'
services:
  bitcoin-service:
    build: .
    env_file:
      - .env
    container_name: "bitcoin-service"
    ports: 
      - "8200:8200"
      - "8201:8201"
    networks:
      - "bcoin"
      - "nginx-proxy"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
  bcoin:
    image: purse/bcoin
    container_name: bcoin
    restart: unless-stopped
    ports:
      #-- Mainnet
      # - "8333:8333"
      # - "8332:8332" # RPC/HTTP
      # - "8334:8334" # Wallet
      #-- Testnet
      - "18333:18333"
      - "18332:18332" # RPC/HTTP
      - "18334:18334"
    environment:
      BCOIN_CONFIG: /data/bcoin.conf
      VIRTUAL_HOST: bcoin.domain.com
      # VIRTUAL_PORT: 8332
      VIRTUAL_PORT: 18332 # Testnest
    networks:
      - "bcoin"
      - "nginx-proxy"
    volumes:
      - ~/.bcoin:/data
      - ${PWD}/secrets/bcoin.conf:/data/bcoin.conf
      - ${PWD}/secrets/wallet.conf:/data/wallet.conf

  nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "nginx-proxy"
    volumes:
      - ./secrets/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  bcoin:
    external:
      name: "bcoin"
  nginx-proxy:
    external:
      name: "nginx-proxy"

```

Any pointers or advice to solve this problem? Documentation is rather scarce but I really want to use bcoin as it makes it a lot easier to manage our business logic.

**Comment by bucko13** [comment]
Have you had a chance to look at the bpanel project? There is a docker setup in that project very similar to what you're trying to setup with two docker services that need to talk to each other, one a bcoin regtest node with wallet services and another the bpanel service for running a server and webapp. Documentation [here](https://github.com/bpanel-org/bpanel#about-the-docker-environment) and docker-compose [here](https://github.com/bpanel-org/bpanel/blob/development/docker-compose.yml) for reference. 

My guess based off the error though is that your ports aren't configured properly between the services. You can confirm that it's not something to do with the bcoin container itself by trying to communicate directly to your node with `bclient`, both from the `host` machine as well as by `exec`ing into the docker container and trying some basic calls like `getInfo`.

**Comment by HOllarves** [comment]
I finally made it work, although it wasn't easy. First I had to stop using jwilder/nginx-proxy, not because the issue was there (at least I couldn't confirm that) but because it's not working properly in a docker swarm. I decided to go for traeffik reverse proxy which not only has enterprise support, but is compatible with docker swarm protocol without additional configuration. 

So what I ended up doing was building the bcoin container from scratch instead of using this repo's image. Then I started the container making sure to attach it to traeffik network manually (or by declaring it in a docker-compose file as an external network), then I made sure to expose both (1)8332 and (1)8334 ports as 2 different applications. Finally I started my application container with the traeffik proxy from a different docker-compose file and it just worked.

bcoin's Dockerfile (copied from this repo):
```
# Copied from https://github.com/bcoin-org/bcoin-docker
FROM node:8-slim

ENV BCOIN_REPO=https://github.com/bcoin-org/bcoin.git \
  BCOIN_DIR=/code/bcoin

# Main-net and Test-net
EXPOSE 8334 8333 8332 18334 18333 18332

RUN apt-get update \
  && apt-get install -y build-essential git make python \
  && mkdir -p $BCOIN_DIR /data \
  && git clone $BCOIN_REPO $BCOIN_DIR \
  && cd $BCOIN_DIR \
  && git checkout tags/v1.0.2  \
  && npm install --production \
  && npm uninstall node-gyp \
  && apt-get remove -y build-essential make python git \
  && apt-get autoremove -y

WORKDIR $BCOIN_DIR

COPY ./scripts/ /code/scripts
RUN chmod +x /code/scripts/launch.sh
RUN chmod +x /code/scripts/mine.sh

CMD ["/code/scripts/launch.sh"]
```

bcoin docker-compose:
```
version: "3"
services:
  bcoin:
    build: .
    container_name: bcoin-node
    restart: unless-stopped
    ports:
      #-- Mainnet
      # - "8333:8333"
      # - "8332:8332" # RPC/HTTP
      # - "8334:8334" # Wallet
      #-- Testnet
      - "18333:18333"
      - "18332:18332" # RPC/HTTP
      - "18334:18334"
    networks:
      - mueve-bitcoin_traefik-net
    volumes:
      - ~/.bcoin:/data
    hostname: localhost
    labels:
      - "traefik.docker.network=mueve-bitcoin_traefik-net"
      - "traefik.bcoin.frontend.rule=Host:bcoin.mueve.com"
      - "traefik.bcoin.backend=bcoin"
      - "traefik.bcoin.port=18332"
      - "traefik.bcoin.frontend.entryPoints=http"
      - "traefik.bcoin-wallet.frontend.rule=Host:bcoin-wallet.mueve.com"
      - "traefik.bcoin-wallet.backend=bcoin-wallet"
      - "traefik.bcoin-wallet.port=18334"
      - "traefik.bcoin-wallet.frontend.entryPoints=http"
networks:
  mueve-bitcoin_traefik-net:
    external: true

```

Finally I was able to connect to the host by doing some sherlock holmes research and finally finding out that even though I was declaring the hostnames (or at least I though I was) as:

```
 labels:
      - "traefik.docker.network=mueve-bitcoin_traefik-net"
      - "traefik.bcoin.frontend.rule=Host:bcoin.mueve.com"
      - "traefik.bcoin.backend=bcoin"
      - "traefik.bcoin.port=18332"
      - "traefik.bcoin.frontend.entryPoints=http"
      - "traefik.bcoin-wallet.frontend.rule=Host:bcoin-wallet.mueve.com"
      - "traefik.bcoin-wallet.backend=bcoin-wallet"
      - "traefik.bcoin-wallet.port=18334"
      - "traefik.bcoin-wallet.frontend.entryPoints=http"

```

The actual hostname is < name-of-container >.< name-of-network >. So basically something like this:

```
	const walletOptions = {
		network: network.type,
		port: network.walletPort,
		apiKey: "secret123",
		host: "bcoin-node.mueve-bitcoin_traefik-net"
	}
```
Hope it helps someone struggling with the same issue. Big shoutout to @enfipy @bucko13 and @pinheadmz for helping me out! :smile:
